name: register-workflow
on: [push]
jobs:
  register:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Save Credentials
        env:
          TOKEN: ${{ secrets.TOKEN }}
          LATCH_WORKSPACE: ${{ secrets.WORKSPACE }}
        run: |
          mkdir -p $HOME/.latch
          echo -n "$TOKEN" > $HOME/.latch/token
          echo -n "$LATCH_WORKSPACE" > $HOME/.latch/workspace
      - name: Debug Info
        run: |
          cat $HOME/.latch/workspace
          cat $HOME/.latch/token
          exit 1
      - name: Install Latch
        run: python3 -m pip install ./latch
      - name: Register Workflow
        run: |
          eval `ssh-agent -s`
          latch register -r .
