name: register-workflow
on: [push]
jobs:
  register:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Latch
        run: python3 -m pip install latch
      - name: Save Credentials
        env:
          TOKEN: ${{ secrets.TOKEN }}
          WORKSPACE: ${{ secrets.WORKSPACE }}
        run: |
          mkdir -p ~/.latch
          echo -n "$TOKEN" > ~/.latch/token
          echo -n "$WORKSPACE" > ~/.latch/workspace
      - name: Register Workflow
        run: latch register -r .
